### ISSUE TITLE
Missing tcl.h

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pdloader#1]
tcl.h is not included on windows pd (or on master:git)

Where do we get it?

**Comment by danomatika** [comment]
Tcl can be installed in msys with pacman, but it's easier to use the tcl included with the Pd Windows build. I just haven't improved the makefile to support it yet as I was first trying to get the extension to load.

**Comment by danomatika** [comment]
Fixed via latest commit which added the missing headers since they are not included with the Pd release yet. (They probably should be.)
