### ISSUE TITLE
package require

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pdloader#2]
In the readme md:
`catch {pdloader::loadfont ../font/DejaVuSansMono.ttf}`

Should't be?:

```
catch {
package require pdloader
pdloader::loadfont ../font/DejaVuSansMono.ttf
}
```

**Comment by danomatika** [comment]
Probably. I wrote it quickly while leaving. Not fully tested yet.

**Comment by danomatika** [comment]
It's a tiny extension and using "load" directly seems to be working fine. Readme has been updated.
