### ISSUE TITLE
Other probably missing headers

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pdloader#3]
Did you look this:
https://sourceforge.net/p/irrational-numbers/code/HEAD/tree/pkgs/extrafont-devkit/trunk/src/extrafont.c

also looks that:

#include <Windows.h>
#include <Wingdi.h>

is needed for windows to load the fonts.

**Comment by danomatika** [comment]
It builds ok without as Windows.h is included via tcl.h and we don't need wingdi.h for the functions that are needed.

**Comment by Lucarda** [comment]
> It builds ok without......

Yes it builds but is rather empty or without any Entry Point.


Also the **AddFontResource** function:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd183326(v=vs.85).aspx
Requires:

Wingdi.h (include Windows.h) 

Here a pic of “pdloader.dll” analyzed with http://www.dependencywalker.com/ for 32bit.

![fontload2](https://user-images.githubusercontent.com/25239522/34061458-36d3c868-e1c7-11e7-8581-db30f8d5bf1e.jpg)



And here “extrafont.dll” (it calls gdi32.dll, the wingdi.h mentioned above) and also have a Funcion Name and an Entry Point:

![fontload1](https://user-images.githubusercontent.com/25239522/34061449-2925025e-e1c7-11e7-9226-0942c0fb1fd6.jpg)

**Comment by danomatika** [comment]
Fixed. It was an issue with the makefile and both headers are indeed needed.
